# Generated by Django 3.0.2 on 2020-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=200)),
                ('benefit', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('authorized', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=200)),
                ('benefit', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('total_max_amount', models.IntegerField()),
            ],
        ),
    ]
