# Generated by Django 3.0.2 on 2020-01-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysure_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
